server:
  port: 9009

spring:
  application:
    name: authorization-server

  profiles:
    include: mysql
    active: sit

  # redis 配置
  redis:
    # 地址
    host: 82.157.53.10
    # 端口，默认为6379
    port: 6379
    # 数据库索引
    database: 8
    # 密码
    password: ZBCY@app9876
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms

logging:
  level:
    org.springframework.web: trace
    org.springframework.security.oauth2: debug
    org.springframework.jdbc.core: debug
    org.springframework.security: trace

# 微信配置
wx:
  miniapp:
    configs:
      - appid: wxf25ba88aa880e9cf #微信小程序的appid
        secret: e9ad6cbaa8961e0caaeda4602156c979 #微信小程序的Secret
        token: #微信小程序消息服务器配置的token
        aesKey: #微信小程序消息服务器配置的EncodingAESKey
        msgDataFormat: JSON

# 支付宝配置
alipay:
  miniapp:
    configs:
        signType: RSA2 #商户生成签名字符串所使用的签名算法类型，目前支持RSA2和RSA，推荐使用RSA2
        charset: UTF-8 #请求和签名使用的字符编码格式，支持GBK和UTF-8
        format: json #参数返回格式
        serverUrl: https://openapi.alipay.com/gateway.do #支付宝网关（固定）



#debug: true

#management:
#  server:
#    port: 8081
#    # 根路径
#  endpoints:
#    web:
#      base-path: /actuator/z
#      # web端允许的路径
#      exposure:
#        include: *